remote_theme: bridgecrewio/yor-theme

site_author: Palo Alto Networks
repo_url: "https://github.com/bridgecrewio/yor/"

edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: false
hljs_style: github-gist
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-get-json

jekyll_get_json:
  - data: menus
    json: './menus.json'
